# Generated by Django 5.1 on 2024-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_coffee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='description',
            field=models.TextField(default=' description = models.TextField(max_length=1000)', max_length=1000),
            preserve_default=False,
        ),
    ]
