# Generated by Django 5.1 on 2024-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_order_total_cost_alter_orderitem_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
