# Generated by Django 5.1 on 2024-12-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0009_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
