# Generated by Django 5.1 on 2024-12-17 09:34

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0013_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(default=datetime.datetime(2024, 12, 17, 9, 34, 35, 783728, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
